<?php if ( ! defined( 'ABSPATH' ) ) exit; ?>
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
 <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
 <title>[Riepilogo_acquisto]</title>
</head>

<body style="margin-top:5px; color:#333;background-color:#f1f1f1;">
	<table cellspacing="0" border="0" width="100%" style="font-family: Arial, Helvetica, sans-serif; font-size:14px; color:#333;" align="center">
	  <tbody>
	  
	   <tr>
		   <td height="30"></td>
	   </tr>
	   
	   <tr>
	    <td style="width:100%;background-color:#f1f1f1;" align="center">
	    
	     <table cellspacing="0" cellpadding="0" border="0" style="width:580px;background-color:#ffffff;padding:10px;margin:0 auto;">
	     
		   <tr>
		    <td height="10"></td>
	       </tr>
	       
		   <tr>
		    <td style="height:25px; color:#333;border-bottom:1px solid #e5e5e5;padding-bottom:20px;">
		     <a href="[BLOG_URL]" style="font-size:20px;text-decoration:none;">
		      [BLOG_NAME]
		     </a>
		     </td>
		  </tr>
		  
		   <tr>
		    <td height="20"></td>
	       </tr>
	       
		  <tr>
		   <td>[EMAIL_HEADER] </td>
		  </tr>
		  
		  <tr>
		   <td height="30" valign="middle">[Riepilogo_acquisto]:</td>
		  </tr>
		  
		  <tr>
		   <td align="center">[CARRELLO]</td>
		  </tr>
		  
		  <tr>
		   <td height="30"></td>
		  </tr>
		  
		  <tr>
		   <td style="background:#f1f1f1;width:100%;padding:10px;">[BONIFICO]</td>
		  </tr>
		  
		  <tr>
		   <td height="30"></td>
		  </tr>
		  
		  <tr>
		  <td style="border-top:1px solid #e5e5e5;" >[EMAIL_FOOTER]</td> 
		  </tr>
		  
		  <tr>
		    <td style="height:5px;border-bottom:1px solid #e5e5e5;"></td>
		  </tr>
		  
		</table>
	   </td>
	  </tr>
	  
	   <tr>
		  <td height="30"></td>
	  </tr>
	  
	</tbody> 
   </table>	 	
 </body>
</html>